//
//  Workspace.swift
//  TuistExampleManifests
//
//  Created by yjc on 2023/07/31.
//

import ProjectDescription

let workspace = Workspace(
    name: "TuistExample", // workspace 이름
    projects: [ // 프로젝트 경로
        "TuistExampleApp"
    ],
    schemes: [], //스킴
    fileHeaderTemplate: nil, // 파일 헤더 ex)Created by yjc ...
    additionalFiles: ["README.md"], // 추가로 포함할 파일
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false, // 스킴을 만들
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant)
    )
)
